title: "Basket of YEGs"
tagline: "Discussions about Edmonton, Politics and Software"
podcast_description: "Troy Pavlek digs into the basket and cracks one open, discussing Edmonton, Politics and Software"
url: "https://basketofyegs.com"
google_analytics_id: "UA-72905999-1"
itunes_url: ""

authors:
  host:
    name: "Troy Pavlek"
    email: "troy@tpavlek.me"
  co-host:
    name: ""
    email: ""
